version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  mymoviedb:
    networks:
      - backend
    image: mongo:latest
    container_name: mymoviedb
    ports:
      - 27017:27017
  movie-app-image:
    networks:
      - backend
    image: varaprasadvs/spring-mongodb-docker:0.0.1
    container_name: movie-app-image
    ports:
      - 8081:8081
    links:
      - mymoviedb
